# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09f6c2e0aa2f21b1f2a9bff34f06da0ae4d2093792ad05d4eff79b06264bc6816159e02cac042d759da8f729d4c4200afd9022c445b67fb18ff5b8c5c9f6a416

test:
  secret_key_base: 6589433c66cd6932c964ab986bad0f9ce783ed5d774901be2125d63431589e510289c35ecf0c3232f48f43e94351aad4588995d70f64417b211d2e1a6635899a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
